apiVersion: apps/v1
kind: Deployment
metadata:
  name: sock-shop-test
  namespace: sock-shop-test
  labels:
    app: sock-shop-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sock-shop-test
  template:
    metadata:
      labels:
        app: sock-shop-test
    spec:
      containers:
      - name: sock-shop-test
        image: idontwanttoshare/sock-shop-test:v1
        args: ["-h", "${SOCK_SHOP_ELB}", "-r", "2", "-c", "2", "-t", "8760h"]
