apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: ${AWS_ACCT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/sock-shop/front-end:latest
        imagePullPolicy: Always
        env:
          - name: DUO_IKEY
            valueFrom:
              secretKeyRef:
                name: duo
                key: ikey
          - name: DUO_SKEY
            valueFrom:
              secretKeyRef:
                name: duo
                key: skey
          - name: DUO_AKEY
            valueFrom:
              secretKeyRef:
                name: duo
                key: akey
          - name: DUO_API_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: duo
                key: api_hostname
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8079
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
