apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: app-first-sec
  region: ${AWS_REGION}
  version: "1.21"

nodeGroups:
  - name: app-first-sec-prod-nodes
    instanceType: t2.medium
    desiredCapacity: 3
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: ${AWS_KEYPAIR_NAME}

vpc:
  subnets:
    private:
      ${VPC_PRIV_SUBNET_1_AZ}: { id: ${VPC_PRIV_SUBNET_1_ID} }
      ${VPC_PRIV_SUBNET_2_AZ}: { id: ${VPC_PRIV_SUBNET_2_ID} }
      ${VPC_PRIV_SUBNET_3_AZ}: { id: ${VPC_PRIV_SUBNET_3_ID} }
